export const dummyTeamMembers = [
    {
      _id: '1',
      name: 'John Smith',
      phone: '+1 (555) 123-4567',
      email: 'john@plumbingpros.com',
      language: 'English',
      workTypes: ['Plumbing', 'HVAC'],
      notes: 'Licensed plumber, available 24/7 for emergencies.',
      isActive: true,
    },
    {
      _id: '2',
      name: 'Sparky Electrical Co.',
      phone: '+1 (555) 987-6543',
      email: 'info@sparky.com',
      language: 'Spanish, English',
      workTypes: ['Electrical', 'Handyman'],
      notes: 'Commercial and residential electrical work.',
      isActive: true,
    },
    {
      _id: '3',
      name: 'Green Thumb Gardening',
      phone: '+1 (555) 456-7890',
      email: 'hello@greenthumb.com',
      language: 'English',
      workTypes: ['Gardening', 'Pest Control'],
      notes: 'Weekly maintenance and one-off jobs.',
      isActive: true,
    },
    {
      _id: '4',
      name: 'A1 Painting Services',
      phone: '+1 (555) 234-5678',
      email: 'info@a1paint.com',
      language: 'English',
      workTypes: ['Painting', 'Carpentry'],
      notes: 'Interior and exterior painting.',
      isActive: true,
    },
  ];